package test;

import java_cup.runtime.*;

parser code {:

  public CalculadoraDePila calc = new CalculadoraDePila();
  
:}

terminal TOKEN_ADD, TOKEN_SUB, TOKEN_MULT, TOKEN_DIV, TOKEN_PUSH, TOKEN_PRINT;
terminal String TOKEN_NUMBER;

non terminal Documento;

non terminal Lista;

non terminal Elemento;

Documento ::= Lista {: System.out.println("DOCUMENTO OK"); :};

Lista ::= Lista Elemento {: :}
        | Elemento {: :};

Elemento ::= TOKEN_ADD {: parser.calc.add(); :}
        |    TOKEN_SUB {: parser.calc.sub(); :}
        |    TOKEN_MULT {: parser.calc.mult(); :}
        |    TOKEN_DIV {: parser.calc.div(); :}
        |    TOKEN_PRINT {: parser.calc.print(); :}
        |    TOKEN_PUSH TOKEN_NUMBER:n 
              {: 
                  Integer numero = Integer.parseInt( n );
                  parser.calc.push( numero ); 
              :};