
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 07 19:47:19 CST 2010
//----------------------------------------------------

package test;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TOKEN_NUMBER = 8;
  public static final int TOKEN_SUB = 3;
  public static final int TOKEN_DIV = 5;
  public static final int EOF = 0;
  public static final int TOKEN_PRINT = 7;
  public static final int TOKEN_MULT = 4;
  public static final int error = 1;
  public static final int TOKEN_ADD = 2;
  public static final int TOKEN_PUSH = 6;
}

